name: Build .NET Core Desktop App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest  
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Execute unit tests
      run: dotnet test akeno/

    - name: Create the app package
      run: dotnet publish -c Release -r win10-x64 akeno/akeno

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Release Package
        path: akeno/akeno/akeno/bin/Release/netcoreapp3.1/win10-x64/
