
name: Generate and deploy docs.

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: mattnotmitt/doxygen-action@v1
      with:
        working-directory: 'akeno/akeno'
        doxyfile-path: 'akeno/Doxygen'

    - name: Upload docs as artifact
      uses: actions/upload-artifact@v2
      with:
        name: Release Package
        path: D:\a\akeno\akeno\html\
